server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**, /api/auth/validate/**, /api/auth/admin/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/notification/mail/**
        - id: profile
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/api/profile/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
